{% set name = "keyrings.google-artifactregistry-auth" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/keyrings.google-artifactregistry-auth-{{ version }}.tar.gz
  sha256: beb037fbf6b0c2ce11d810319fdc180cab8865daa2a16b109c3af73182ffe44d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools-scm >=3.4.1
    - pip
  run:
    - python >={{ python_min }}
    - keyring
    - google-auth
    - requests
    - pluggy

test:
  imports:
    - google_artifactregistry_auth
    - keyrings
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/GoogleCloudPlatform/artifact-registry-python-tools
  summary: Keyring backend for Google Auth tokens
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - SandorSzalma1
